
#EXTM3U

#EXTINF:-1 tvg-id="" tvg-name="Magnum P.I. S01 E01" tvg-logo="https://image.tmdb.org/t/p/w300/ocvc5Xw5xmiM8Yf3U2VkmsqNGxT.jpg" group-title="Séries | Amazon Prime",Magnum P.I. S01 E01
http://lxls.mx:80/series/994153115/101217/208907.mp4
#EXTINF:-1 tvg-id="" tvg-name="Magnum P.I. S01 E02" tvg-logo="https://image.tmdb.org/t/p/w300/6aIYFeMaohCw1n6IJ2lyUcWm2iu.jpg" group-title="Séries | Amazon Prime",Magnum P.I. S01 E02
http://lxls.mx:80/series/994153115/101217/208906.mp4
#EXTINF:-1 tvg-id="" tvg-name="Magnum P.I. S01 E03" tvg-logo="http://lxls.mx:8080/images/2640de61855e97dcca2c9ae3c0798822.jpg" group-title="Séries | Amazon Prime",Magnum P.I. S01 E03
http://lxls.mx:80/series/994153115/101217/208905.mp4
#EXTINF:-1 tvg-id="" tvg-name="Magnum P.I. S01 E04" tvg-logo="https://image.tmdb.org/t/p/w300/nJB8qmSB0OWCPqs1sjJEeexeiMf.jpg" group-title="Séries | Amazon Prime",Magnum P.I. S01 E04
http://lxls.mx:80/series/994153115/101217/208904.mp4
#EXTINF:-1 tvg-id="" tvg-name="Magnum P.I. S01 E05" tvg-logo="http://lxls.mx:8080/images/2640de61855e97dcca2c9ae3c0798822.jpg" group-title="Séries | Amazon Prime",Magnum P.I. S01 E05
http://lxls.mx:80/series/994153115/101217/208903.mp4
#EXTINF:-1 tvg-id="" tvg-name="Magnum P.I. S01 E06" tvg-logo="https://image.tmdb.org/t/p/w300/p1N1pwbKZihsMlytErwTGmxTLWP.jpg" group-title="Séries | Amazon Prime",Magnum P.I. S01 E06
http://lxls.mx:80/series/994153115/101217/208902.mp4
#EXTINF:-1 tvg-id="" tvg-name="Magnum P.I. S01 E07" tvg-logo="https://image.tmdb.org/t/p/w300/j35t0blPGrXpGmIXWi5JorJiN2n.jpg" group-title="Séries | Amazon Prime",Magnum P.I. S01 E07
http://lxls.mx:80/series/994153115/101217/208901.mp4
#EXTINF:-1 tvg-id="" tvg-name="Magnum P.I. S01 E08" tvg-logo="http://lxls.mx:8080/images/2640de61855e97dcca2c9ae3c0798822.jpg" group-title="Séries | Amazon Prime",Magnum P.I. S01 E08
http://lxls.mx:80/series/994153115/101217/208900.mp4
#EXTINF:-1 tvg-id="" tvg-name="Magnum P.I. S01 E09" tvg-logo="https://image.tmdb.org/t/p/w300/aikSOzabg5efRV9L49dfcENYmO7.jpg" group-title="Séries | Amazon Prime",Magnum P.I. S01 E09
http://lxls.mx:80/series/994153115/101217/208899.mp4
#EXTINF:-1 tvg-id="" tvg-name="Magnum P.I. S01 E10" tvg-logo="https://image.tmdb.org/t/p/w300/bSNGmnuI6i4hSooaBBb3RBtB36w.jpg" group-title="Séries | Amazon Prime",Magnum P.I. S01 E10
http://lxls.mx:80/series/994153115/101217/208898.mp4
#EXTINF:-1 tvg-id="" tvg-name="Magnum P.I. S01 E11" tvg-logo="https://image.tmdb.org/t/p/w300/ztnXaIm7j2MUIulBoR3EjlfGO2j.jpg" group-title="Séries | Amazon Prime",Magnum P.I. S01 E11
http://lxls.mx:80/series/994153115/101217/207736.mp4
#EXTINF:-1 tvg-id="" tvg-name="Magnum P.I. S01 E12" tvg-logo="https://image.tmdb.org/t/p/w300/pLpSxIhITSaH8F6DmT054D6WHK6.jpg" group-title="Séries | Amazon Prime",Magnum P.I. S01 E12
http://lxls.mx:80/series/994153115/101217/207735.mp4
#EXTINF:-1 tvg-id="" tvg-name="Magnum P.I. S01 E13" tvg-logo="http://lxls.mx:8080/images/2640de61855e97dcca2c9ae3c0798822.jpg" group-title="Séries | Amazon Prime",Magnum P.I. S01 E13
http://lxls.mx:80/series/994153115/101217/207734.mp4
#EXTINF:-1 tvg-id="" tvg-name="Magnum P.I. S01 E14" tvg-logo="https://image.tmdb.org/t/p/w300/tl0Hc53f7SY3sz2KpdoB7MvU99s.jpg" group-title="Séries | Amazon Prime",Magnum P.I. S01 E14
http://lxls.mx:80/series/994153115/101217/207062.mp4
#EXTINF:-1 tvg-id="" tvg-name="Magnum P.I. S01 E15" tvg-logo="https://image.tmdb.org/t/p/w300/3hlzQDIRCCRmdWOlseIuzcTXZyx.jpg" group-title="Séries | Amazon Prime",Magnum P.I. S01 E15
http://lxls.mx:80/series/994153115/101217/205079.mp4
#EXTINF:-1 tvg-id="" tvg-name="Magnum P.I. S01 E16" tvg-logo="https://image.tmdb.org/t/p/w300/469TKf0YRlAZcM1cPSwxVebo8so.jpg" group-title="Séries | Amazon Prime",Magnum P.I. S01 E16
http://lxls.mx:80/series/994153115/101217/205562.mp4
#EXTINF:-1 tvg-id="" tvg-name="Magnum P.I. S01 E17" tvg-logo="https://image.tmdb.org/t/p/w300/zUPDZx8DrkEzYCEGseLai0N0H68.jpg" group-title="Séries | Amazon Prime",Magnum P.I. S01 E17
http://lxls.mx:80/series/994153115/101217/205561.mp4
#EXTINF:-1 tvg-id="" tvg-name="Magnum P.I. S01 E18" tvg-logo="https://image.tmdb.org/t/p/w300/zUPDZx8DrkEzYCEGseLai0N0H68.jpg" group-title="Séries | Amazon Prime",Magnum P.I. S01 E18
http://lxls.mx:80/series/994153115/101217/205078.mp4
#EXTINF:-1 tvg-id="" tvg-name="Magnum P.I. S01 E19" tvg-logo="https://image.tmdb.org/t/p/w300/zCwzmM5MfyLGFHLQ50XjcdffouV.jpg" group-title="Séries | Amazon Prime",Magnum P.I. S01 E19
http://lxls.mx:80/series/994153115/101217/205077.mp4
#EXTINF:-1 tvg-id="" tvg-name="Magnum P.I. S01 E20" tvg-logo="http://lxls.mx:8080/images/2640de61855e97dcca2c9ae3c0798822.jpg" group-title="Séries | Amazon Prime",Magnum P.I. S01 E20
http://lxls.mx:80/series/994153115/101217/205076.mp4
#EXTINF:-1 tvg-id="" tvg-name="Magnum P.I. S01 E21" tvg-logo="https://image.tmdb.org/t/p/w300/gDlIedX6MUG4OquyP5Ki0Xwj1kQ.jpg" group-title="Séries | Amazon Prime",Magnum P.I. S01 E21
http://lxls.mx:80/series/994153115/101217/205075.mp4
#EXTINF:-1 tvg-id="" tvg-name="Magnum P.I. S02 E01" tvg-logo="http://lxls.mx:8080/images/2640de61855e97dcca2c9ae3c0798822.jpg" group-title="Séries | Amazon Prime",Magnum P.I. S02 E01
http://lxls.mx:80/series/994153115/101217/180081.mp4
#EXTINF:-1 tvg-id="" tvg-name="Magnum P.I. S02 E02" tvg-logo="http://lxls.mx:8080/images/2640de61855e97dcca2c9ae3c0798822.jpg" group-title="Séries | Amazon Prime",Magnum P.I. S02 E02
http://lxls.mx:80/series/994153115/101217/180080.mp4
#EXTINF:-1 tvg-id="" tvg-name="Magnum P.I. S02 E03" tvg-logo="https://image.tmdb.org/t/p/w300/rHwXnCH97pQm9LKvrkffFjqOdFd.jpg" group-title="Séries | Amazon Prime",Magnum P.I. S02 E03
http://lxls.mx:80/series/994153115/101217/180079.mp4
#EXTINF:-1 tvg-id="" tvg-name="Magnum P.I. S02 E04" tvg-logo="http://lxls.mx:8080/images/2640de61855e97dcca2c9ae3c0798822.jpg" group-title="Séries | Amazon Prime",Magnum P.I. S02 E04
http://lxls.mx:80/series/994153115/101217/180078.mp4
#EXTINF:-1 tvg-id="" tvg-name="Magnum P.I. S02 E05" tvg-logo="https://image.tmdb.org/t/p/w300/7xfgCPbuQCnBGZpVSTf7UWZawtI.jpg" group-title="Séries | Amazon Prime",Magnum P.I. S02 E05
http://lxls.mx:80/series/994153115/101217/180077.mp4
#EXTINF:-1 tvg-id="" tvg-name="Magnum P.I. S02 E06" tvg-logo="https://image.tmdb.org/t/p/w300/8D7YibbbXUWSnpnXOFbaIcyAZvF.jpg" group-title="Séries | Amazon Prime",Magnum P.I. S02 E06
http://lxls.mx:80/series/994153115/101217/180076.mp4
#EXTINF:-1 tvg-id="" tvg-name="Magnum P.I. S02 E07" tvg-logo="http://lxls.mx:8080/images/2640de61855e97dcca2c9ae3c0798822.jpg" group-title="Séries | Amazon Prime",Magnum P.I. S02 E07
http://lxls.mx:80/series/994153115/101217/180075.mp4
#EXTINF:-1 tvg-id="" tvg-name="Magnum P.I. S02 E08" tvg-logo="https://image.tmdb.org/t/p/w300/xqzaji6RxL2BAf9aWC6qaRo4gxb.jpg" group-title="Séries | Amazon Prime",Magnum P.I. S02 E08
http://lxls.mx:80/series/994153115/101217/180074.mp4
#EXTINF:-1 tvg-id="" tvg-name="Magnum P.I. S02 E09" tvg-logo="https://image.tmdb.org/t/p/w300/ujkonwmM77t2Mz5o82O3URHUpLw.jpg" group-title="Séries | Amazon Prime",Magnum P.I. S02 E09
http://lxls.mx:80/series/994153115/101217/180073.mp4
#EXTINF:-1 tvg-id="" tvg-name="Magnum P.I. S02 E10" tvg-logo="http://lxls.mx:8080/images/2640de61855e97dcca2c9ae3c0798822.jpg" group-title="Séries | Amazon Prime",Magnum P.I. S02 E10
http://lxls.mx:80/series/994153115/101217/180072.mp4
#EXTINF:-1 tvg-id="" tvg-name="Magnum P.I. S02 E11" tvg-logo="https://image.tmdb.org/t/p/w300/dyynhySvqDIHlec30iiIHIStOL4.jpg" group-title="Séries | Amazon Prime",Magnum P.I. S02 E11
http://lxls.mx:80/series/994153115/101217/180071.mp4
#EXTINF:-1 tvg-id="" tvg-name="Magnum P.I. S02 E12" tvg-logo="http://lxls.mx:8080/images/2640de61855e97dcca2c9ae3c0798822.jpg" group-title="Séries | Amazon Prime",Magnum P.I. S02 E12
http://lxls.mx:80/series/994153115/101217/180070.mp4
#EXTINF:-1 tvg-id="" tvg-name="Magnum P.I. S02 E13" tvg-logo="https://image.tmdb.org/t/p/w300/5SiUAINQX7PzsLY570bJqfPvk9q.jpg" group-title="Séries | Amazon Prime",Magnum P.I. S02 E13
http://lxls.mx:80/series/994153115/101217/180069.mp4
#EXTINF:-1 tvg-id="" tvg-name="Magnum P.I. S02 E14" tvg-logo="https://image.tmdb.org/t/p/w300/cZJoS2OcXSOz3sWvrRmqDxQRZ88.jpg" group-title="Séries | Amazon Prime",Magnum P.I. S02 E14
http://lxls.mx:80/series/994153115/101217/180068.mp4
#EXTINF:-1 tvg-id="" tvg-name="Magnum P.I. S02 E15" tvg-logo="https://image.tmdb.org/t/p/w300/4IIsNGtl5cttEbHif4wh2WJSqIu.jpg" group-title="Séries | Amazon Prime",Magnum P.I. S02 E15
http://lxls.mx:80/series/994153115/101217/180067.mp4
#EXTINF:-1 tvg-id="" tvg-name="Magnum P.I. S02 E16" tvg-logo="https://image.tmdb.org/t/p/w300/zH37bQ4Nyuj7Xc0NciuQlAAgqMV.jpg" group-title="Séries | Amazon Prime",Magnum P.I. S02 E16
http://lxls.mx:80/series/994153115/101217/180066.mp4
#EXTINF:-1 tvg-id="" tvg-name="Magnum P.I. S02 E17" tvg-logo="https://image.tmdb.org/t/p/w300/lGiIKAmSe5RVkGdkvYmYj2U8uLv.jpg" group-title="Séries | Amazon Prime",Magnum P.I. S02 E17
http://lxls.mx:80/series/994153115/101217/180065.mp4
#EXTINF:-1 tvg-id="" tvg-name="Magnum P.I. S02 E18" tvg-logo="https://image.tmdb.org/t/p/w300/s4cwcxrf2BGAE01ubeVwC3dErpZ.jpg" group-title="Séries | Amazon Prime",Magnum P.I. S02 E18
http://lxls.mx:80/series/994153115/101217/180064.mp4
#EXTINF:-1 tvg-id="" tvg-name="Magnum P.I. S02 E19" tvg-logo="https://image.tmdb.org/t/p/w300/uzow7K4ajznvVgKPC80LjPHXMLG.jpg" group-title="Séries | Amazon Prime",Magnum P.I. S02 E19
http://lxls.mx:80/series/994153115/101217/180063.mp4
#EXTINF:-1 tvg-id="" tvg-name="Magnum P.I. S02 E20" tvg-logo="https://image.tmdb.org/t/p/w300/6S0S6NQf60UAoltLlGRu97RcFDa.jpg" group-title="Séries | Amazon Prime",Magnum P.I. S02 E20
http://lxls.mx:80/series/994153115/101217/180062.mp4
#EXTINF:-1 tvg-id="" tvg-name="Magnum P.I. S03 E01" tvg-logo="http://lxls.mx:8080/images/2640de61855e97dcca2c9ae3c0798822.jpg" group-title="Séries | Amazon Prime",Magnum P.I. S03 E01
http://lxls.mx:80/series/994153115/101217/151619.mp4
#EXTINF:-1 tvg-id="" tvg-name="Magnum P.I. S03 E02" tvg-logo="https://image.tmdb.org/t/p/w300/z32VOtYMYKWEokwyHcwRHcypBGt.jpg" group-title="Séries | Amazon Prime",Magnum P.I. S03 E02
http://lxls.mx:80/series/994153115/101217/150800.mp4
#EXTINF:-1 tvg-id="" tvg-name="Magnum P.I. S03 E03" tvg-logo="https://image.tmdb.org/t/p/w300/5K5Ahzq0LzCchkzzuZXoLXUrnNE.jpg" group-title="Séries | Amazon Prime",Magnum P.I. S03 E03
http://lxls.mx:80/series/994153115/101217/150574.mp4
#EXTINF:-1 tvg-id="" tvg-name="Magnum P.I. S03 E04" tvg-logo="https://image.tmdb.org/t/p/w300/gIbxt7XeSKBmnm052jZjDONxJzu.jpg" group-title="Séries | Amazon Prime",Magnum P.I. S03 E04
http://lxls.mx:80/series/994153115/101217/149327.mp4
#EXTINF:-1 tvg-id="" tvg-name="Magnum P.I. S03 E05" tvg-logo="https://image.tmdb.org/t/p/w300/aLW8QSbW6T1Yfa9ZImmbtyf1W6G.jpg" group-title="Séries | Amazon Prime",Magnum P.I. S03 E05
http://lxls.mx:80/series/994153115/101217/148057.mp4
#EXTINF:-1 tvg-id="" tvg-name="Magnum P.I. S03 E06" tvg-logo="https://image.tmdb.org/t/p/w300/xJzWJ1el6pSZYC98Af3zXtDRsT1.jpg" group-title="Séries | Amazon Prime",Magnum P.I. S03 E06
http://lxls.mx:80/series/994153115/101217/147785.mp4
#EXTINF:-1 tvg-id="" tvg-name="Magnum P.I. S03 E07" tvg-logo="http://lxls.mx:8080/images/2640de61855e97dcca2c9ae3c0798822.jpg" group-title="Séries | Amazon Prime",Magnum P.I. S03 E07
http://lxls.mx:80/series/994153115/101217/147599.mp4
#EXTINF:-1 tvg-id="" tvg-name="Magnum P.I. S03 E08" tvg-logo="http://lxls.mx:8080/images/2640de61855e97dcca2c9ae3c0798822.jpg" group-title="Séries | Amazon Prime",Magnum P.I. S03 E08
http://lxls.mx:80/series/994153115/101217/147500.mp4
#EXTINF:-1 tvg-id="" tvg-name="Magnum P.I. S03 E09" tvg-logo="https://image.tmdb.org/t/p/w300/dcGmwoqow8hHH68ES22WVgSoXrn.jpg" group-title="Séries | Amazon Prime",Magnum P.I. S03 E09
http://lxls.mx:80/series/994153115/101217/146653.mp4
#EXTINF:-1 tvg-id="" tvg-name="Magnum P.I. S03 E10" tvg-logo="http://lxls.mx:8080/images/2640de61855e97dcca2c9ae3c0798822.jpg" group-title="Séries | Amazon Prime",Magnum P.I. S03 E10
http://lxls.mx:80/series/994153115/101217/145486.mp4
#EXTINF:-1 tvg-id="" tvg-name="Magnum P.I. S03 E11" tvg-logo="http://lxls.mx:8080/images/2640de61855e97dcca2c9ae3c0798822.jpg" group-title="Séries | Amazon Prime",Magnum P.I. S03 E11
http://lxls.mx:80/series/994153115/101217/145485.mp4
#EXTINF:-1 tvg-id="" tvg-name="Magnum P.I. S03 E12" tvg-logo="http://lxls.mx:8080/images/2640de61855e97dcca2c9ae3c0798822.jpg" group-title="Séries | Amazon Prime",Magnum P.I. S03 E12
http://lxls.mx:80/series/994153115/101217/143829.mp4
#EXTINF:-1 tvg-id="" tvg-name="Magnum P.I. S03 E13" tvg-logo="http://lxls.mx:8080/images/2640de61855e97dcca2c9ae3c0798822.jpg" group-title="Séries | Amazon Prime",Magnum P.I. S03 E13
http://lxls.mx:80/series/994153115/101217/142527.mp4
#EXTINF:-1 tvg-id="" tvg-name="Magnum P.I. S03 E14" tvg-logo="https://image.tmdb.org/t/p/w300/3DnL9WfL6pdgKetbJjRUDHS7rsK.jpg" group-title="Séries | Amazon Prime",Magnum P.I. S03 E14
http://lxls.mx:80/series/994153115/101217/142526.mp4
#EXTINF:-1 tvg-id="" tvg-name="Magnum P.I. S03 E15" tvg-logo="http://lxls.mx:8080/images/2640de61855e97dcca2c9ae3c0798822.jpg" group-title="Séries | Amazon Prime",Magnum P.I. S03 E15
http://lxls.mx:80/series/994153115/101217/142525.mp4
#EXTINF:-1 tvg-id="" tvg-name="Magnum P.I. S03 E16" tvg-logo="https://image.tmdb.org/t/p/w300/umN2z2f26LIiVl7U7Nm6jAvC1Ii.jpg" group-title="Séries | Amazon Prime",Magnum P.I. S03 E16
http://lxls.mx:80/series/994153115/101217/141652.mp4