
#EXTM3U

#EXTINF:-1 tvg-id="" tvg-name="Marvels M.O.D.O.K. S01 E01" tvg-logo="http://lxls.mx:8080/images/878d3fe608879af6560d20f60a3eaa26.jpg" group-title="Séries | Star+",Marvels M.O.D.O.K. S01 E01
http://lxls.mx:80/series/994153115/101217/144348.mp4
#EXTINF:-1 tvg-id="" tvg-name="Marvels M.O.D.O.K. S01 E02" tvg-logo="https://image.tmdb.org/t/p/w300/fAzZXEY6uqSHeZ7ugxz9FqCfAkg.jpg" group-title="Séries | Star+",Marvels M.O.D.O.K. S01 E02
http://lxls.mx:80/series/994153115/101217/144347.mp4
#EXTINF:-1 tvg-id="" tvg-name="Marvels M.O.D.O.K. S01 E03" tvg-logo="https://image.tmdb.org/t/p/w300/wVVduYQCD2hmwiAYhMgcOI9A91u.jpg" group-title="Séries | Star+",Marvels M.O.D.O.K. S01 E03
http://lxls.mx:80/series/994153115/101217/144346.mp4
#EXTINF:-1 tvg-id="" tvg-name="Marvels M.O.D.O.K. S01 E04" tvg-logo="https://image.tmdb.org/t/p/w300/9b6nizaj6uCYCRNtVeJ1SUT4do1.jpg" group-title="Séries | Star+",Marvels M.O.D.O.K. S01 E04
http://lxls.mx:80/series/994153115/101217/144345.mp4
#EXTINF:-1 tvg-id="" tvg-name="Marvels M.O.D.O.K. S01 E05" tvg-logo="http://lxls.mx:8080/images/878d3fe608879af6560d20f60a3eaa26.jpg" group-title="Séries | Star+",Marvels M.O.D.O.K. S01 E05
http://lxls.mx:80/series/994153115/101217/144344.mp4
#EXTINF:-1 tvg-id="" tvg-name="Marvels M.O.D.O.K. S01 E06" tvg-logo="http://lxls.mx:8080/images/878d3fe608879af6560d20f60a3eaa26.jpg" group-title="Séries | Star+",Marvels M.O.D.O.K. S01 E06
http://lxls.mx:80/series/994153115/101217/144343.mp4
#EXTINF:-1 tvg-id="" tvg-name="Marvels M.O.D.O.K. S01 E07" tvg-logo="http://lxls.mx:8080/images/878d3fe608879af6560d20f60a3eaa26.jpg" group-title="Séries | Star+",Marvels M.O.D.O.K. S01 E07
http://lxls.mx:80/series/994153115/101217/144342.mp4
#EXTINF:-1 tvg-id="" tvg-name="Marvels M.O.D.O.K. S01 E08" tvg-logo="https://image.tmdb.org/t/p/w300/4fsxiicymbbeKYFJOb3tQtCjg0Z.jpg" group-title="Séries | Star+",Marvels M.O.D.O.K. S01 E08
http://lxls.mx:80/series/994153115/101217/144341.mp4
#EXTINF:-1 tvg-id="" tvg-name="Marvels M.O.D.O.K. S01 E09" tvg-logo="https://image.tmdb.org/t/p/w300/5sgCzbxKUHZZ6HyAS7a76q1i9vf.jpg" group-title="Séries | Star+",Marvels M.O.D.O.K. S01 E09
http://lxls.mx:80/series/994153115/101217/144340.mp4
#EXTINF:-1 tvg-id="" tvg-name="Marvels M.O.D.O.K. S01 E10" tvg-logo="http://lxls.mx:8080/images/878d3fe608879af6560d20f60a3eaa26.jpg" group-title="Séries | Star+",Marvels M.O.D.O.K. S01 E10
http://lxls.mx:80/series/994153115/101217/144339.mp4