
#EXTM3U

#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S01 E01" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S01 E01
http://cdnrede.com:80/series/rosanapin/rosana@123/212594.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S01 E02" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S01 E02
http://cdnrede.com:80/series/rosanapin/rosana@123/212595.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S01 E03" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S01 E03
http://cdnrede.com:80/series/rosanapin/rosana@123/212596.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S01 E04" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S01 E04
http://cdnrede.com:80/series/rosanapin/rosana@123/212597.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S01 E05" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S01 E05
http://cdnrede.com:80/series/rosanapin/rosana@123/212598.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S01 E06" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S01 E06
http://cdnrede.com:80/series/rosanapin/rosana@123/212599.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S01 E07" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S01 E07
http://cdnrede.com:80/series/rosanapin/rosana@123/212600.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S01 E08" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S01 E08
http://cdnrede.com:80/series/rosanapin/rosana@123/212601.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S01 E09" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S01 E09
http://cdnrede.com:80/series/rosanapin/rosana@123/212602.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S01 E10" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S01 E10
http://cdnrede.com:80/series/rosanapin/rosana@123/212603.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S01 E11" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S01 E11
http://cdnrede.com:80/series/rosanapin/rosana@123/212604.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S01 E12" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S01 E12
http://cdnrede.com:80/series/rosanapin/rosana@123/212605.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S01 E13" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S01 E13
http://cdnrede.com:80/series/rosanapin/rosana@123/212606.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S01 E14" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S01 E14
http://cdnrede.com:80/series/rosanapin/rosana@123/212607.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S01 E15" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S01 E15
http://cdnrede.com:80/series/rosanapin/rosana@123/212608.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S01 E16" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S01 E16
http://cdnrede.com:80/series/rosanapin/rosana@123/212609.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S01 E17" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S01 E17
http://cdnrede.com:80/series/rosanapin/rosana@123/212610.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S01 E18" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S01 E18
http://cdnrede.com:80/series/rosanapin/rosana@123/212611.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S01 E19" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S01 E19
http://cdnrede.com:80/series/rosanapin/rosana@123/212612.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S01 E20" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S01 E20
http://cdnrede.com:80/series/rosanapin/rosana@123/212613.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S02 E01" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S02 E01
http://cdnrede.com:80/series/rosanapin/rosana@123/212614.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S02 E02" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S02 E02
http://cdnrede.com:80/series/rosanapin/rosana@123/212615.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S02 E03" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S02 E03
http://cdnrede.com:80/series/rosanapin/rosana@123/212616.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S02 E04" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S02 E04
http://cdnrede.com:80/series/rosanapin/rosana@123/212617.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S02 E05" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S02 E05
http://cdnrede.com:80/series/rosanapin/rosana@123/212618.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S02 E06" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S02 E06
http://cdnrede.com:80/series/rosanapin/rosana@123/212619.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S02 E07" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S02 E07
http://cdnrede.com:80/series/rosanapin/rosana@123/212620.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S02 E08" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S02 E08
http://cdnrede.com:80/series/rosanapin/rosana@123/212621.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S02 E09" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S02 E09
http://cdnrede.com:80/series/rosanapin/rosana@123/212622.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S02 E10" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S02 E10
http://cdnrede.com:80/series/rosanapin/rosana@123/212623.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S02 E11" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S02 E11
http://cdnrede.com:80/series/rosanapin/rosana@123/212624.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S02 E12" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S02 E12
http://cdnrede.com:80/series/rosanapin/rosana@123/212625.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S02 E13" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S02 E13
http://cdnrede.com:80/series/rosanapin/rosana@123/212626.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S02 E14" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S02 E14
http://cdnrede.com:80/series/rosanapin/rosana@123/212627.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S02 E15" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S02 E15
http://cdnrede.com:80/series/rosanapin/rosana@123/212628.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S02 E16" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S02 E16
http://cdnrede.com:80/series/rosanapin/rosana@123/212629.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S02 E17" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S02 E17
http://cdnrede.com:80/series/rosanapin/rosana@123/212630.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S02 E18" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S02 E18
http://cdnrede.com:80/series/rosanapin/rosana@123/212631.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S02 E19" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S02 E19
http://cdnrede.com:80/series/rosanapin/rosana@123/212632.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S02 E20" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S02 E20
http://cdnrede.com:80/series/rosanapin/rosana@123/212633.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S03 E01" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S03 E01
http://cdnrede.com:80/series/rosanapin/rosana@123/212634.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S03 E02" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S03 E02
http://cdnrede.com:80/series/rosanapin/rosana@123/212635.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S03 E03" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S03 E03
http://cdnrede.com:80/series/rosanapin/rosana@123/212636.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S03 E04" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S03 E04
http://cdnrede.com:80/series/rosanapin/rosana@123/212637.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S03 E05" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S03 E05
http://cdnrede.com:80/series/rosanapin/rosana@123/212638.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S03 E06" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S03 E06
http://cdnrede.com:80/series/rosanapin/rosana@123/212639.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S03 E07" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S03 E07
http://cdnrede.com:80/series/rosanapin/rosana@123/212640.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S03 E08" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S03 E08
http://cdnrede.com:80/series/rosanapin/rosana@123/212641.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S03 E09" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S03 E09
http://cdnrede.com:80/series/rosanapin/rosana@123/212642.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S03 E10" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S03 E10
http://cdnrede.com:80/series/rosanapin/rosana@123/212643.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S03 E11" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S03 E11
http://cdnrede.com:80/series/rosanapin/rosana@123/212644.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S03 E12" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S03 E12
http://cdnrede.com:80/series/rosanapin/rosana@123/212645.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S03 E13" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S03 E13
http://cdnrede.com:80/series/rosanapin/rosana@123/212646.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S03 E14" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S03 E14
http://cdnrede.com:80/series/rosanapin/rosana@123/212647.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S03 E15" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S03 E15
http://cdnrede.com:80/series/rosanapin/rosana@123/222271.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S03 E16" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S03 E16
http://cdnrede.com:80/series/rosanapin/rosana@123/222272.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S04 E01" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S04 E01
http://cdnrede.com:80/series/rosanapin/rosana@123/222274.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S04 E02" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S04 E02
http://cdnrede.com:80/series/rosanapin/rosana@123/222261.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S04 E03" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S04 E03
http://cdnrede.com:80/series/rosanapin/rosana@123/222262.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S04 E04" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S04 E04
http://cdnrede.com:80/series/rosanapin/rosana@123/222275.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S04 E05" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S04 E05
http://cdnrede.com:80/series/rosanapin/rosana@123/222263.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S04 E06" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S04 E06
http://cdnrede.com:80/series/rosanapin/rosana@123/222276.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S04 E07" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S04 E07
http://cdnrede.com:80/series/rosanapin/rosana@123/222277.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S04 E08" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S04 E08
http://cdnrede.com:80/series/rosanapin/rosana@123/222264.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S04 E09" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S04 E09
http://cdnrede.com:80/series/rosanapin/rosana@123/222265.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S04 E10" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S04 E10
http://cdnrede.com:80/series/rosanapin/rosana@123/222278.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S04 E11" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S04 E11
http://cdnrede.com:80/series/rosanapin/rosana@123/222279.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S04 E12" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S04 E12
http://cdnrede.com:80/series/rosanapin/rosana@123/222266.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S04 E13" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S04 E13
http://cdnrede.com:80/series/rosanapin/rosana@123/222280.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S04 E14" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S04 E14
http://cdnrede.com:80/series/rosanapin/rosana@123/222267.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S04 E15" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S04 E15
http://cdnrede.com:80/series/rosanapin/rosana@123/222281.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S04 E16" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S04 E16
http://cdnrede.com:80/series/rosanapin/rosana@123/222268.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S04 E17" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S04 E17
http://cdnrede.com:80/series/rosanapin/rosana@123/222282.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S04 E18" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S04 E18
http://cdnrede.com:80/series/rosanapin/rosana@123/222269.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S04 E19" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S04 E19
http://cdnrede.com:80/series/rosanapin/rosana@123/222270.mp4
#EXTINF:-1 tvg-id="" tvg-name="MAGNUM P.I S04 E20" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/son6AuCmsoPWmRgPP6fKQacV9wt.jpg" group-title="SERIE- MAGNUM P.I",MAGNUM P.I S04 E20
http://cdnrede.com:80/series/rosanapin/rosana@123/222283.mp4