
#EXTM3U

#EXTINF:-1 tvg-id="" tvg-name="MARVELS M.O.D.O.K S01 E01" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/2kXRzRjQZs9kAIm3K9MkQgsZR9C.jpg" group-title="SERIE- MARVELS M.O.D.O.K",MARVELS M.O.D.O.K S01 E01
http://cdnrede.com:80/series/rosanapin/rosana@123/206840.mp4
#EXTINF:-1 tvg-id="" tvg-name="MARVELS M.O.D.O.K S01 E02" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/2kXRzRjQZs9kAIm3K9MkQgsZR9C.jpg" group-title="SERIE- MARVELS M.O.D.O.K",MARVELS M.O.D.O.K S01 E02
http://cdnrede.com:80/series/rosanapin/rosana@123/206841.mp4
#EXTINF:-1 tvg-id="" tvg-name="MARVELS M.O.D.O.K S01 E03" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/2kXRzRjQZs9kAIm3K9MkQgsZR9C.jpg" group-title="SERIE- MARVELS M.O.D.O.K",MARVELS M.O.D.O.K S01 E03
http://cdnrede.com:80/series/rosanapin/rosana@123/206842.mp4