
#EXTM3U

#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S01 E01" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S01 E01
http://cdnrede.com:80/series/rosanapin/rosana@123/166895.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S01 E02" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S01 E02
http://cdnrede.com:80/series/rosanapin/rosana@123/166896.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S01 E03" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S01 E03
http://cdnrede.com:80/series/rosanapin/rosana@123/166897.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S01 E04" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S01 E04
http://cdnrede.com:80/series/rosanapin/rosana@123/166898.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S01 E05" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S01 E05
http://cdnrede.com:80/series/rosanapin/rosana@123/166899.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S01 E06" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S01 E06
http://cdnrede.com:80/series/rosanapin/rosana@123/166900.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S01 E07" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S01 E07
http://cdnrede.com:80/series/rosanapin/rosana@123/166901.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S01 E08" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S01 E08
http://cdnrede.com:80/series/rosanapin/rosana@123/166902.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S01 E09" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S01 E09
http://cdnrede.com:80/series/rosanapin/rosana@123/166903.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S01 E10" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S01 E10
http://cdnrede.com:80/series/rosanapin/rosana@123/166904.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S01 E11" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S01 E11
http://cdnrede.com:80/series/rosanapin/rosana@123/166905.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S01 E12" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S01 E12
http://cdnrede.com:80/series/rosanapin/rosana@123/166906.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S01 E13" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S01 E13
http://cdnrede.com:80/series/rosanapin/rosana@123/166907.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S01 E14" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S01 E14
http://cdnrede.com:80/series/rosanapin/rosana@123/166908.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S01 E15" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S01 E15
http://cdnrede.com:80/series/rosanapin/rosana@123/166909.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S01 E16" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S01 E16
http://cdnrede.com:80/series/rosanapin/rosana@123/166910.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S01 E17" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S01 E17
http://cdnrede.com:80/series/rosanapin/rosana@123/166911.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S01 E18" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S01 E18
http://cdnrede.com:80/series/rosanapin/rosana@123/166912.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S01 E19" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S01 E19
http://cdnrede.com:80/series/rosanapin/rosana@123/166913.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S01 E20" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S01 E20
http://cdnrede.com:80/series/rosanapin/rosana@123/166914.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S01 E21" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S01 E21
http://cdnrede.com:80/series/rosanapin/rosana@123/166915.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S01 E22" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S01 E22
http://cdnrede.com:80/series/rosanapin/rosana@123/166916.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S02 E01" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S02 E01
http://cdnrede.com:80/series/rosanapin/rosana@123/166917.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S02 E02" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S02 E02
http://cdnrede.com:80/series/rosanapin/rosana@123/166918.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S02 E03" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S02 E03
http://cdnrede.com:80/series/rosanapin/rosana@123/166919.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S02 E04" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S02 E04
http://cdnrede.com:80/series/rosanapin/rosana@123/166920.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S02 E05" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S02 E05
http://cdnrede.com:80/series/rosanapin/rosana@123/166921.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S02 E06" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S02 E06
http://cdnrede.com:80/series/rosanapin/rosana@123/166922.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S02 E07" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S02 E07
http://cdnrede.com:80/series/rosanapin/rosana@123/166923.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S02 E08" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S02 E08
http://cdnrede.com:80/series/rosanapin/rosana@123/166924.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S02 E09" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S02 E09
http://cdnrede.com:80/series/rosanapin/rosana@123/166925.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S02 E10" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S02 E10
http://cdnrede.com:80/series/rosanapin/rosana@123/166926.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S02 E11" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S02 E11
http://cdnrede.com:80/series/rosanapin/rosana@123/166927.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S02 E12" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S02 E12
http://cdnrede.com:80/series/rosanapin/rosana@123/166928.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S02 E13" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S02 E13
http://cdnrede.com:80/series/rosanapin/rosana@123/166929.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S02 E14" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S02 E14
http://cdnrede.com:80/series/rosanapin/rosana@123/166930.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S02 E15" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S02 E15
http://cdnrede.com:80/series/rosanapin/rosana@123/166931.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S02 E16" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S02 E16
http://cdnrede.com:80/series/rosanapin/rosana@123/166932.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S02 E17" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S02 E17
http://cdnrede.com:80/series/rosanapin/rosana@123/166933.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S02 E18" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S02 E18
http://cdnrede.com:80/series/rosanapin/rosana@123/166934.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S02 E19" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S02 E19
http://cdnrede.com:80/series/rosanapin/rosana@123/166935.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S02 E20" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S02 E20
http://cdnrede.com:80/series/rosanapin/rosana@123/166936.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S02 E21" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S02 E21
http://cdnrede.com:80/series/rosanapin/rosana@123/166937.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S02 E22" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S02 E22
http://cdnrede.com:80/series/rosanapin/rosana@123/166938.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S03 E01" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S03 E01
http://cdnrede.com:80/series/rosanapin/rosana@123/172564.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S03 E02" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S03 E02
http://cdnrede.com:80/series/rosanapin/rosana@123/173858.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S03 E03" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S03 E03
http://cdnrede.com:80/series/rosanapin/rosana@123/172667.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S03 E04" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S03 E04
http://cdnrede.com:80/series/rosanapin/rosana@123/172639.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S03 E05" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S03 E05
http://cdnrede.com:80/series/rosanapin/rosana@123/172668.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S03 E06" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S03 E06
http://cdnrede.com:80/series/rosanapin/rosana@123/173859.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S03 E07" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S03 E07
http://cdnrede.com:80/series/rosanapin/rosana@123/172565.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S03 E08" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S03 E08
http://cdnrede.com:80/series/rosanapin/rosana@123/173860.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S03 E09" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S03 E09
http://cdnrede.com:80/series/rosanapin/rosana@123/172566.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S03 E10" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S03 E10
http://cdnrede.com:80/series/rosanapin/rosana@123/172567.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S03 E11" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S03 E11
http://cdnrede.com:80/series/rosanapin/rosana@123/173861.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S03 E12" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S03 E12
http://cdnrede.com:80/series/rosanapin/rosana@123/219191.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S03 E13" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S03 E13
http://cdnrede.com:80/series/rosanapin/rosana@123/219192.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S03 E14" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S03 E14
http://cdnrede.com:80/series/rosanapin/rosana@123/219193.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S03 E15" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S03 E15
http://cdnrede.com:80/series/rosanapin/rosana@123/219194.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S03 E16" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S03 E16
http://cdnrede.com:80/series/rosanapin/rosana@123/219195.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S03 E17" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S03 E17
http://cdnrede.com:80/series/rosanapin/rosana@123/219196.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S03 E18" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S03 E18
http://cdnrede.com:80/series/rosanapin/rosana@123/219197.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S03 E19" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S03 E19
http://cdnrede.com:80/series/rosanapin/rosana@123/219198.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S03 E20" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S03 E20
http://cdnrede.com:80/series/rosanapin/rosana@123/219199.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S03 E21" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S03 E21
http://cdnrede.com:80/series/rosanapin/rosana@123/219200.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S04 E01" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S04 E01
http://cdnrede.com:80/series/rosanapin/rosana@123/220393.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S04 E02" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S04 E02
http://cdnrede.com:80/series/rosanapin/rosana@123/220394.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S04 E03" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S04 E03
http://cdnrede.com:80/series/rosanapin/rosana@123/220395.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S04 E04" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S04 E04
http://cdnrede.com:80/series/rosanapin/rosana@123/220396.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S04 E05" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S04 E05
http://cdnrede.com:80/series/rosanapin/rosana@123/220397.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S04 E06" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S04 E06
http://cdnrede.com:80/series/rosanapin/rosana@123/220398.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S04 E07" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S04 E07
http://cdnrede.com:80/series/rosanapin/rosana@123/220399.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S04 E08" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S04 E08
http://cdnrede.com:80/series/rosanapin/rosana@123/220400.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S04 E09" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S04 E09
http://cdnrede.com:80/series/rosanapin/rosana@123/220401.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S04 E10" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S04 E10
http://cdnrede.com:80/series/rosanapin/rosana@123/220402.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S04 E11" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S04 E11
http://cdnrede.com:80/series/rosanapin/rosana@123/220403.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S04 E12" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S04 E12
http://cdnrede.com:80/series/rosanapin/rosana@123/220404.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S04 E13" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S04 E13
http://cdnrede.com:80/series/rosanapin/rosana@123/220405.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S04 E14" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S04 E14
http://cdnrede.com:80/series/rosanapin/rosana@123/220406.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S04 E15" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S04 E15
http://cdnrede.com:80/series/rosanapin/rosana@123/220407.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S04 E16" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S04 E16
http://cdnrede.com:80/series/rosanapin/rosana@123/220408.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S04 E17" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S04 E17
http://cdnrede.com:80/series/rosanapin/rosana@123/220409.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S04 E18" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S04 E18
http://cdnrede.com:80/series/rosanapin/rosana@123/220410.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S05 E01" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S05 E01
http://cdnrede.com:80/series/rosanapin/rosana@123/220411.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S05 E02" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S05 E02
http://cdnrede.com:80/series/rosanapin/rosana@123/220412.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S05 E03" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S05 E03
http://cdnrede.com:80/series/rosanapin/rosana@123/220413.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S05 E04" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S05 E04
http://cdnrede.com:80/series/rosanapin/rosana@123/220414.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S05 E05" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S05 E05
http://cdnrede.com:80/series/rosanapin/rosana@123/220415.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S05 E06" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S05 E06
http://cdnrede.com:80/series/rosanapin/rosana@123/220416.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S05 E07" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S05 E07
http://cdnrede.com:80/series/rosanapin/rosana@123/222241.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S05 E08" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S05 E08
http://cdnrede.com:80/series/rosanapin/rosana@123/222242.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S05 E09" tvg-logo="https://image.tmdb.org/t/p/w600_and_h900_bestv2/ttzrYMdsKWR8PTRLw7uo4noqaOJ.jpg" group-title="SERIE- S.W.A.T",S.W.A.T. S05 E09
http://cdnrede.com:80/series/rosanapin/rosana@123/222243.mp4