
#EXTM3U

#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S01 E01" tvg-logo="http://lxls.mx:8080/images/107c7a624ae026f1fb48be7089ea30f9.jpg" group-title="Séries | Globoplay",S.W.A.T. S01 E01
http://lxls.mx:80/series/994153115/101217/215687.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S01 E02" tvg-logo="http://lxls.mx:8080/images/107c7a624ae026f1fb48be7089ea30f9.jpg" group-title="Séries | Globoplay",S.W.A.T. S01 E02
http://lxls.mx:80/series/994153115/101217/215686.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S01 E03" tvg-logo="http://lxls.mx:8080/images/107c7a624ae026f1fb48be7089ea30f9.jpg" group-title="Séries | Globoplay",S.W.A.T. S01 E03
http://lxls.mx:80/series/994153115/101217/215685.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S01 E04" tvg-logo="https://image.tmdb.org/t/p/w300/q14AUilWmpsruwtvd4vQdxXxV5A.jpg" group-title="Séries | Globoplay",S.W.A.T. S01 E04
http://lxls.mx:80/series/994153115/101217/215684.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S01 E05" tvg-logo="https://image.tmdb.org/t/p/w300/bW66kBXOZyYYh2q4gJSWL4k0lH6.jpg" group-title="Séries | Globoplay",S.W.A.T. S01 E05
http://lxls.mx:80/series/994153115/101217/215683.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S01 E06" tvg-logo="https://image.tmdb.org/t/p/w300/8mYfOWJwX1FpBcpmtiFWS2a8Btb.jpg" group-title="Séries | Globoplay",S.W.A.T. S01 E06
http://lxls.mx:80/series/994153115/101217/215682.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S01 E07" tvg-logo="http://lxls.mx:8080/images/107c7a624ae026f1fb48be7089ea30f9.jpg" group-title="Séries | Globoplay",S.W.A.T. S01 E07
http://lxls.mx:80/series/994153115/101217/215681.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S01 E08" tvg-logo="https://image.tmdb.org/t/p/w300/3pPA6L3SJllX2xgJqAik27naP7O.jpg" group-title="Séries | Globoplay",S.W.A.T. S01 E08
http://lxls.mx:80/series/994153115/101217/215680.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S01 E09" tvg-logo="https://image.tmdb.org/t/p/w300/jPv8GEW7x7THFIX1qPY5GUuvbcU.jpg" group-title="Séries | Globoplay",S.W.A.T. S01 E09
http://lxls.mx:80/series/994153115/101217/215679.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S01 E10" tvg-logo="http://lxls.mx:8080/images/107c7a624ae026f1fb48be7089ea30f9.jpg" group-title="Séries | Globoplay",S.W.A.T. S01 E10
http://lxls.mx:80/series/994153115/101217/215678.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S01 E11" tvg-logo="http://lxls.mx:8080/images/107c7a624ae026f1fb48be7089ea30f9.jpg" group-title="Séries | Globoplay",S.W.A.T. S01 E11
http://lxls.mx:80/series/994153115/101217/215677.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S01 E12" tvg-logo="http://lxls.mx:8080/images/107c7a624ae026f1fb48be7089ea30f9.jpg" group-title="Séries | Globoplay",S.W.A.T. S01 E12
http://lxls.mx:80/series/994153115/101217/215676.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S01 E13" tvg-logo="http://lxls.mx:8080/images/107c7a624ae026f1fb48be7089ea30f9.jpg" group-title="Séries | Globoplay",S.W.A.T. S01 E13
http://lxls.mx:80/series/994153115/101217/215675.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S01 E14" tvg-logo="http://lxls.mx:8080/images/107c7a624ae026f1fb48be7089ea30f9.jpg" group-title="Séries | Globoplay",S.W.A.T. S01 E14
http://lxls.mx:80/series/994153115/101217/215674.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S01 E15" tvg-logo="http://lxls.mx:8080/images/107c7a624ae026f1fb48be7089ea30f9.jpg" group-title="Séries | Globoplay",S.W.A.T. S01 E15
http://lxls.mx:80/series/994153115/101217/215673.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S01 E16" tvg-logo="http://lxls.mx:8080/images/107c7a624ae026f1fb48be7089ea30f9.jpg" group-title="Séries | Globoplay",S.W.A.T. S01 E16
http://lxls.mx:80/series/994153115/101217/215672.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S01 E17" tvg-logo="https://image.tmdb.org/t/p/w300/mrldnF1NdLvl2xqQWATDj1sxJYm.jpg" group-title="Séries | Globoplay",S.W.A.T. S01 E17
http://lxls.mx:80/series/994153115/101217/215671.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S01 E18" tvg-logo="http://lxls.mx:8080/images/107c7a624ae026f1fb48be7089ea30f9.jpg" group-title="Séries | Globoplay",S.W.A.T. S01 E18
http://lxls.mx:80/series/994153115/101217/215670.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S01 E19" tvg-logo="https://image.tmdb.org/t/p/w300/oZugqn7ez6P9NVhVd3COXOq0IXC.jpg" group-title="Séries | Globoplay",S.W.A.T. S01 E19
http://lxls.mx:80/series/994153115/101217/215669.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S01 E20" tvg-logo="http://lxls.mx:8080/images/107c7a624ae026f1fb48be7089ea30f9.jpg" group-title="Séries | Globoplay",S.W.A.T. S01 E20
http://lxls.mx:80/series/994153115/101217/215668.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S01 E21" tvg-logo="http://lxls.mx:8080/images/107c7a624ae026f1fb48be7089ea30f9.jpg" group-title="Séries | Globoplay",S.W.A.T. S01 E21
http://lxls.mx:80/series/994153115/101217/215667.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S01 E22" tvg-logo="http://lxls.mx:8080/images/107c7a624ae026f1fb48be7089ea30f9.jpg" group-title="Séries | Globoplay",S.W.A.T. S01 E22
http://lxls.mx:80/series/994153115/101217/215666.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S02 E01" tvg-logo="https://image.tmdb.org/t/p/w300/emujgxFDyJzIqNtbF3djGFzQGG2.jpg" group-title="Séries | Globoplay",S.W.A.T. S02 E01
http://lxls.mx:80/series/994153115/101217/214605.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S02 E02" tvg-logo="http://lxls.mx:8080/images/107c7a624ae026f1fb48be7089ea30f9.jpg" group-title="Séries | Globoplay",S.W.A.T. S02 E02
http://lxls.mx:80/series/994153115/101217/214604.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S02 E03" tvg-logo="http://lxls.mx:8080/images/107c7a624ae026f1fb48be7089ea30f9.jpg" group-title="Séries | Globoplay",S.W.A.T. S02 E03
http://lxls.mx:80/series/994153115/101217/214603.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S02 E04" tvg-logo="http://lxls.mx:8080/images/107c7a624ae026f1fb48be7089ea30f9.jpg" group-title="Séries | Globoplay",S.W.A.T. S02 E04
http://lxls.mx:80/series/994153115/101217/214602.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S02 E05" tvg-logo="http://lxls.mx:8080/images/107c7a624ae026f1fb48be7089ea30f9.jpg" group-title="Séries | Globoplay",S.W.A.T. S02 E05
http://lxls.mx:80/series/994153115/101217/214601.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S02 E06" tvg-logo="http://lxls.mx:8080/images/107c7a624ae026f1fb48be7089ea30f9.jpg" group-title="Séries | Globoplay",S.W.A.T. S02 E06
http://lxls.mx:80/series/994153115/101217/214600.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S02 E07" tvg-logo="http://lxls.mx:8080/images/107c7a624ae026f1fb48be7089ea30f9.jpg" group-title="Séries | Globoplay",S.W.A.T. S02 E07
http://lxls.mx:80/series/994153115/101217/214584.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S02 E08" tvg-logo="https://image.tmdb.org/t/p/w300/pigsmurrr4dR3zVmV9Q3I4ITKOw.jpg" group-title="Séries | Globoplay",S.W.A.T. S02 E08
http://lxls.mx:80/series/994153115/101217/214583.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S02 E09" tvg-logo="https://image.tmdb.org/t/p/w300/9s9klQyBXdReUiGi8iuD8VTXtSf.jpg" group-title="Séries | Globoplay",S.W.A.T. S02 E09
http://lxls.mx:80/series/994153115/101217/214582.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S02 E10" tvg-logo="http://lxls.mx:8080/images/107c7a624ae026f1fb48be7089ea30f9.jpg" group-title="Séries | Globoplay",S.W.A.T. S02 E10
http://lxls.mx:80/series/994153115/101217/214581.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S02 E11" tvg-logo="https://image.tmdb.org/t/p/w300/ikE288XWKfBevitTNkm63hPs7rh.jpg" group-title="Séries | Globoplay",S.W.A.T. S02 E11
http://lxls.mx:80/series/994153115/101217/214580.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S02 E12" tvg-logo="http://lxls.mx:8080/images/107c7a624ae026f1fb48be7089ea30f9.jpg" group-title="Séries | Globoplay",S.W.A.T. S02 E12
http://lxls.mx:80/series/994153115/101217/214579.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S02 E13" tvg-logo="http://lxls.mx:8080/images/107c7a624ae026f1fb48be7089ea30f9.jpg" group-title="Séries | Globoplay",S.W.A.T. S02 E13
http://lxls.mx:80/series/994153115/101217/214240.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S02 E14" tvg-logo="https://image.tmdb.org/t/p/w300/vgau0dArFzpwlSaCTg5GgZCUiPJ.jpg" group-title="Séries | Globoplay",S.W.A.T. S02 E14
http://lxls.mx:80/series/994153115/101217/214239.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S02 E15" tvg-logo="http://lxls.mx:8080/images/107c7a624ae026f1fb48be7089ea30f9.jpg" group-title="Séries | Globoplay",S.W.A.T. S02 E15
http://lxls.mx:80/series/994153115/101217/214238.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S02 E16" tvg-logo="https://image.tmdb.org/t/p/w300/beJ7QJHpC4VMp7U4NqDBPBQNNEz.jpg" group-title="Séries | Globoplay",S.W.A.T. S02 E16
http://lxls.mx:80/series/994153115/101217/214237.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S02 E17" tvg-logo="http://lxls.mx:8080/images/107c7a624ae026f1fb48be7089ea30f9.jpg" group-title="Séries | Globoplay",S.W.A.T. S02 E17
http://lxls.mx:80/series/994153115/101217/214236.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S02 E18" tvg-logo="https://image.tmdb.org/t/p/w300/8Ll6YGEE1i7Qg0s6kv6h0tss86j.jpg" group-title="Séries | Globoplay",S.W.A.T. S02 E18
http://lxls.mx:80/series/994153115/101217/214235.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S02 E19" tvg-logo="http://lxls.mx:8080/images/107c7a624ae026f1fb48be7089ea30f9.jpg" group-title="Séries | Globoplay",S.W.A.T. S02 E19
http://lxls.mx:80/series/994153115/101217/214234.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S02 E20" tvg-logo="http://lxls.mx:8080/images/107c7a624ae026f1fb48be7089ea30f9.jpg" group-title="Séries | Globoplay",S.W.A.T. S02 E20
http://lxls.mx:80/series/994153115/101217/214233.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S02 E21" tvg-logo="http://lxls.mx:8080/images/107c7a624ae026f1fb48be7089ea30f9.jpg" group-title="Séries | Globoplay",S.W.A.T. S02 E21
http://lxls.mx:80/series/994153115/101217/214232.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S02 E22" tvg-logo="https://image.tmdb.org/t/p/w300/mJfj6JrurDWijU9pgiCdYhbo5ur.jpg" group-title="Séries | Globoplay",S.W.A.T. S02 E22
http://lxls.mx:80/series/994153115/101217/214231.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S02 E23" tvg-logo="http://lxls.mx:8080/images/107c7a624ae026f1fb48be7089ea30f9.jpg" group-title="Séries | Globoplay",S.W.A.T. S02 E23
http://lxls.mx:80/series/994153115/101217/214230.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S03 E01" tvg-logo="https://image.tmdb.org/t/p/w300/xRFlDto2vEGffSjI87RMvsy5mvM.jpg" group-title="Séries | Globoplay",S.W.A.T. S03 E01
http://lxls.mx:80/series/994153115/101217/191792.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S03 E02" tvg-logo="http://lxls.mx:8080/images/107c7a624ae026f1fb48be7089ea30f9.jpg" group-title="Séries | Globoplay",S.W.A.T. S03 E02
http://lxls.mx:80/series/994153115/101217/191791.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S03 E03" tvg-logo="http://lxls.mx:8080/images/107c7a624ae026f1fb48be7089ea30f9.jpg" group-title="Séries | Globoplay",S.W.A.T. S03 E03
http://lxls.mx:80/series/994153115/101217/191790.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S03 E04" tvg-logo="http://lxls.mx:8080/images/107c7a624ae026f1fb48be7089ea30f9.jpg" group-title="Séries | Globoplay",S.W.A.T. S03 E04
http://lxls.mx:80/series/994153115/101217/191631.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S03 E05" tvg-logo="http://lxls.mx:8080/images/107c7a624ae026f1fb48be7089ea30f9.jpg" group-title="Séries | Globoplay",S.W.A.T. S03 E05
http://lxls.mx:80/series/994153115/101217/190759.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S03 E06" tvg-logo="http://lxls.mx:8080/images/107c7a624ae026f1fb48be7089ea30f9.jpg" group-title="Séries | Globoplay",S.W.A.T. S03 E06
http://lxls.mx:80/series/994153115/101217/190737.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S03 E07" tvg-logo="https://image.tmdb.org/t/p/w300/5xJmzM8pjf8lAGOO5oOipR6UzvM.jpg" group-title="Séries | Globoplay",S.W.A.T. S03 E07
http://lxls.mx:80/series/994153115/101217/189282.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S03 E08" tvg-logo="http://lxls.mx:8080/images/107c7a624ae026f1fb48be7089ea30f9.jpg" group-title="Séries | Globoplay",S.W.A.T. S03 E08
http://lxls.mx:80/series/994153115/101217/189281.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S03 E09" tvg-logo="http://lxls.mx:8080/images/107c7a624ae026f1fb48be7089ea30f9.jpg" group-title="Séries | Globoplay",S.W.A.T. S03 E09
http://lxls.mx:80/series/994153115/101217/188203.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S03 E10" tvg-logo="http://lxls.mx:8080/images/107c7a624ae026f1fb48be7089ea30f9.jpg" group-title="Séries | Globoplay",S.W.A.T. S03 E10
http://lxls.mx:80/series/994153115/101217/188202.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S03 E11" tvg-logo="https://image.tmdb.org/t/p/w300/25AaqzxTLJew5vWFhzenb1FvViY.jpg" group-title="Séries | Globoplay",S.W.A.T. S03 E11
http://lxls.mx:80/series/994153115/101217/187881.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S03 E12" tvg-logo="https://image.tmdb.org/t/p/w300/uDjCj1BoPxd5s06gI2lZ4YJ8SpV.jpg" group-title="Séries | Globoplay",S.W.A.T. S03 E12
http://lxls.mx:80/series/994153115/101217/187764.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S03 E13" tvg-logo="https://image.tmdb.org/t/p/w300/mK2yya9AyOqAlVMn5tZcFRmyAXN.jpg" group-title="Séries | Globoplay",S.W.A.T. S03 E13
http://lxls.mx:80/series/994153115/101217/186345.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S03 E14" tvg-logo="https://image.tmdb.org/t/p/w300/qipZdKI5cyzW01smNNPDBkLFVqE.jpg" group-title="Séries | Globoplay",S.W.A.T. S03 E14
http://lxls.mx:80/series/994153115/101217/186296.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S03 E15" tvg-logo="http://lxls.mx:8080/images/107c7a624ae026f1fb48be7089ea30f9.jpg" group-title="Séries | Globoplay",S.W.A.T. S03 E15
http://lxls.mx:80/series/994153115/101217/185831.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S03 E16" tvg-logo="http://lxls.mx:8080/images/107c7a624ae026f1fb48be7089ea30f9.jpg" group-title="Séries | Globoplay",S.W.A.T. S03 E16
http://lxls.mx:80/series/994153115/101217/183911.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S03 E17" tvg-logo="http://lxls.mx:8080/images/107c7a624ae026f1fb48be7089ea30f9.jpg" group-title="Séries | Globoplay",S.W.A.T. S03 E17
http://lxls.mx:80/series/994153115/101217/183910.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S03 E18" tvg-logo="http://lxls.mx:8080/images/107c7a624ae026f1fb48be7089ea30f9.jpg" group-title="Séries | Globoplay",S.W.A.T. S03 E18
http://lxls.mx:80/series/994153115/101217/180917.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S03 E19" tvg-logo="http://lxls.mx:8080/images/107c7a624ae026f1fb48be7089ea30f9.jpg" group-title="Séries | Globoplay",S.W.A.T. S03 E19
http://lxls.mx:80/series/994153115/101217/180381.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S03 E20" tvg-logo="http://lxls.mx:8080/images/107c7a624ae026f1fb48be7089ea30f9.jpg" group-title="Séries | Globoplay",S.W.A.T. S03 E20
http://lxls.mx:80/series/994153115/101217/180380.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S03 E21" tvg-logo="https://image.tmdb.org/t/p/w300/m1YYNzFc6oL2dI7BAn3OBMs2ds.jpg" group-title="Séries | Globoplay",S.W.A.T. S03 E21
http://lxls.mx:80/series/994153115/101217/180379.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S04 E01" tvg-logo="http://lxls.mx:8080/images/107c7a624ae026f1fb48be7089ea30f9.jpg" group-title="Séries | Globoplay",S.W.A.T. S04 E01
http://lxls.mx:80/series/994153115/101217/150051.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S04 E02" tvg-logo="http://lxls.mx:8080/images/107c7a624ae026f1fb48be7089ea30f9.jpg" group-title="Séries | Globoplay",S.W.A.T. S04 E02
http://lxls.mx:80/series/994153115/101217/150049.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S04 E03" tvg-logo="https://image.tmdb.org/t/p/w300/zou1IWytKMvu4uCnT9fB3nUiJxi.jpg" group-title="Séries | Globoplay",S.W.A.T. S04 E03
http://lxls.mx:80/series/994153115/101217/150046.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S04 E04" tvg-logo="https://image.tmdb.org/t/p/w300/hEoSRThn3WoBU08XiS7BHI4tQ4y.jpg" group-title="Séries | Globoplay",S.W.A.T. S04 E04
http://lxls.mx:80/series/994153115/101217/150043.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S04 E05" tvg-logo="https://image.tmdb.org/t/p/w300/o06szLE1qaSBiStOsABqIBTAN0G.jpg" group-title="Séries | Globoplay",S.W.A.T. S04 E05
http://lxls.mx:80/series/994153115/101217/150041.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S04 E06" tvg-logo="https://image.tmdb.org/t/p/w300/qOE7ovfyhwnrvpjry7J8gILRGQQ.jpg" group-title="Séries | Globoplay",S.W.A.T. S04 E06
http://lxls.mx:80/series/994153115/101217/150038.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S04 E07" tvg-logo="http://lxls.mx:8080/images/107c7a624ae026f1fb48be7089ea30f9.jpg" group-title="Séries | Globoplay",S.W.A.T. S04 E07
http://lxls.mx:80/series/994153115/101217/150036.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S04 E08" tvg-logo="https://image.tmdb.org/t/p/w300/3hrFngU9A4srhMJIMkVmQ0jKtmb.jpg" group-title="Séries | Globoplay",S.W.A.T. S04 E08
http://lxls.mx:80/series/994153115/101217/150034.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S04 E09" tvg-logo="https://image.tmdb.org/t/p/w300/asnvszKZ6AGEls4IFrbXiGGyG97.jpg" group-title="Séries | Globoplay",S.W.A.T. S04 E09
http://lxls.mx:80/series/994153115/101217/150032.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S04 E10" tvg-logo="http://lxls.mx:8080/images/107c7a624ae026f1fb48be7089ea30f9.jpg" group-title="Séries | Globoplay",S.W.A.T. S04 E10
http://lxls.mx:80/series/994153115/101217/150031.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S04 E11" tvg-logo="http://lxls.mx:8080/images/107c7a624ae026f1fb48be7089ea30f9.jpg" group-title="Séries | Globoplay",S.W.A.T. S04 E11
http://lxls.mx:80/series/994153115/101217/150028.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S04 E12" tvg-logo="https://image.tmdb.org/t/p/w300/2tIj8vpDKzTP732i2ffIXmRu4cQ.jpg" group-title="Séries | Globoplay",S.W.A.T. S04 E12
http://lxls.mx:80/series/994153115/101217/150025.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S04 E13" tvg-logo="https://image.tmdb.org/t/p/w300/aOUjIoMi00oHtN2l2a8MjXVqi9N.jpg" group-title="Séries | Globoplay",S.W.A.T. S04 E13
http://lxls.mx:80/series/994153115/101217/150024.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S04 E14" tvg-logo="https://image.tmdb.org/t/p/w300/th9k2kwfin0rVixpCvRIcEbH4Xy.jpg" group-title="Séries | Globoplay",S.W.A.T. S04 E14
http://lxls.mx:80/series/994153115/101217/150021.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S04 E15" tvg-logo="https://image.tmdb.org/t/p/w300/eFu6PhK2jluZevVDyoGoR79qsaE.jpg" group-title="Séries | Globoplay",S.W.A.T. S04 E15
http://lxls.mx:80/series/994153115/101217/150020.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S04 E16" tvg-logo="https://image.tmdb.org/t/p/w300/jdlaqzDVUTQENUXwgTgPlxEw1dV.jpg" group-title="Séries | Globoplay",S.W.A.T. S04 E16
http://lxls.mx:80/series/994153115/101217/150017.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S04 E17" tvg-logo="https://image.tmdb.org/t/p/w300/txYBtPg26W4GmwjkfGY1J6w3lF5.jpg" group-title="Séries | Globoplay",S.W.A.T. S04 E17
http://lxls.mx:80/series/994153115/101217/150015.mp4
#EXTINF:-1 tvg-id="" tvg-name="S.W.A.T. S04 E18" tvg-logo="https://image.tmdb.org/t/p/w300/121IeaO2EqKzDHh7ZEJI5gnI9iG.jpg" group-title="Séries | Globoplay",S.W.A.T. S04 E18
http://lxls.mx:80/series/994153115/101217/150012.mp4